/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = process.env.SUPABASE_PROJECT_ID || "xeojamsdfsqjtxwfgdj"
export const supabaseUrl = process.env.SUPABASE_URL || "https://xeojamsdfsqjtxwfgdj.supabase.co"
export const publicAnonKey = process.env.SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlb29qYW1zZGZzcWp0eHdmZ2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDMwNjAsImV4cCI6MjA3NTM3OTA2MH0.KZUjm5xdiIe1NiDYOyzhwHZu9L_6XDQXjxQWJ6GWTpk"